language: node_js

env:
  global:
    - CXX=g++-4.8

node_js:
  - "stable"
  - "4.4.5"

matrix:
  include:
    - node_js: "4.4.5"
      os: osx

script:
  - npm test

after_script:
  - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"

before_deploy:
  - chmod 555 scripts/package.sh && scripts/package.sh

deploy:
  - provider: s3
    access_key_id:
      secure: REPLACE_ME
    secret_access_key:
      secure: REPLACE_ME
    bucket: ds-server-artifacts
    skip_cleanup: true
    acl: public_read
    local_dir: build
    upload-dir: $TRAVIS_REPO_SLUG
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: REPLACE_ME
    file_glob: true
    file:
      - "build/*.tar.gz"
      - "build/*.zip"
    on:
      tags: true

plugins:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8